In [1]:
from scipy import stats
import numpy as np
import scipy.integrate as integrate
import matplotlib.pyplot as plt
from matplotlib import colors
from IPython.display import Image

### Getting familiarised with matrix operations

In [11]:
M=np.array( ((1,2),(3,4)) )
N=np.array( ((1.1,1.2),(1.3,1.4)) )

In [606]:
M

array([[1, 2],
       [3, 4]])

transpose

In [646]:
M.T

array([[1, 3],
       [2, 4]])

conjugate transpose

In [654]:
np.matrix(M).getH()

matrix([[1, 3],
        [2, 4]])

sum

In [607]:
M+N

array([[ 2.1,  3.2],
       [ 4.3,  5.4]])

matrix product

In [608]:
M.dot(N)

array([[ 3.7,  4. ],
       [ 8.5,  9.2]])

element-by-element product

In [613]:
M*N

array([[ 1.1,  2.4],
       [ 3.9,  5.6]])

inversion

In [612]:
Minv=np.linalg.inv(M)
M.dot(Minv)

array([[  1.00000000e+00,   0.00000000e+00],
       [  8.88178420e-16,   1.00000000e+00]])

Cholesky decomposition: $~~~{\bf M}={\bf L}\cdot{\bf L}^\dagger$

In [656]:
np.linalg.cholesky(M)

LinAlgError: Matrix is not positive definite

In [618]:
D=np.array( ((2,-1,0),(-1,2,-1),(0,-1,2)) )
print(D)
np.linalg.cholesky(D)

[[ 2 -1  0]
 [-1  2 -1]
 [ 0 -1  2]]


array([[ 1.41421356,  0.        ,  0.        ],
       [-0.70710678,  1.22474487,  0.        ],
       [ 0.        , -0.81649658,  1.15470054]])

Exponentiation

In [628]:
print('10^M = \n',10**M)
print('   ')
print('exp(M) = \n',np.exp(M))
print('   ')
print('ln(M) = \n',np.log(M))

10^M = 
 [[   10   100]
 [ 1000 10000]]
   
exp(M) = 
 [[  2.71828183   7.3890561 ]
 [ 20.08553692  54.59815003]]
   
ln(M) = 
 [[ 0.          0.69314718]
 [ 1.09861229  1.38629436]]


Within-matrix operations

In [639]:
print('np.sum(M) = ',np.sum(M))
print('np.sum(M,axis=0) = ',np.sum(M,axis=0))
print('np.sum(M,axis=1) = ',np.sum(M,axis=1))
print(np.sum(M,axis=1,keepdims=True))

np.sum(M) =  10
np.sum(M,axis=0) =  [4 6]
np.sum(M,axis=1) =  [3 7]
[[3]
 [7]]
